schema: schema.graphql
generates:
  ./src/graphql/resolvers-types.ts:
    config:
      useIndexSignature: true
      contextType: ./models#Context
      mappers:
        User: ./models#UserModel
    plugins:
      - typescript
      - typescript-resolvers
